/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formularios;

import Controladores.cargos;
import Controladores.consultas;
import Controladores.ventas;
import java.awt.Point;
import java.awt.Rectangle;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.lang.invoke.MethodHandles;
import java.time.Year;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import modelos.pizzaItem;

/**
 *
 * @author yisus
 */
public class fmr_Cargo_Descargo extends javax.swing.JFrame {

    /**
     * Creates new form fmr_Cargo_Descargo
     */
    ventas v = new ventas();
   consultas cd = new consultas();
   List<pizzaItem> Detalle_Lista = new ArrayList<>();
   List<pizzaItem> listaPAraSolucionarUnBugQueMeDioPerezaArreglarBien = new ArrayList<>(); 
   
    public fmr_Cargo_Descargo() {
        initComponents();
        v.fnt_fechaActual(lbl_Fecha);
        lbl_descripcionDes.setVisible(false);
        txt_descripcionDes.setVisible(false);
        scroll_desc.setVisible(false);
    }
    boolean verificarTipo=true;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_proovB = new javax.swing.JTextField();
        lbl_Fecha = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_bucarPr = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaItem = new javax.swing.JTable();
        txt_item = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaResumen = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btn_tipoAccion = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        scroll_desc = new javax.swing.JScrollPane();
        txt_descripcionDes = new javax.swing.JTextArea();
        lbl_descripcionDes = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_nombreProv = new javax.swing.JTextField();
        txt_idProv = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        lbl_total = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setText("Proveedor");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 90, 57, 16);

        jLabel2.setText("Fecha:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 10, 50, 16);

        txt_proovB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_proovBActionPerformed(evt);
            }
        });
        txt_proovB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_proovBKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_proovBKeyTyped(evt);
            }
        });
        jPanel1.add(txt_proovB);
        txt_proovB.setBounds(80, 80, 340, 30);

        lbl_Fecha.setText("--------");
        jPanel1.add(lbl_Fecha);
        lbl_Fecha.setBounds(90, 10, 130, 16);

        tabla_bucarPr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_bucarPrMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla_bucarPr);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(80, 120, 340, 100);

        jScrollPane2.setViewportView(tablaItem);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(510, 120, 452, 100);

        txt_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_itemActionPerformed(evt);
            }
        });
        txt_item.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_itemKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_itemKeyTyped(evt);
            }
        });
        jPanel1.add(txt_item);
        txt_item.setBounds(580, 80, 380, 30);

        jLabel3.setText("Item");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(530, 90, 40, 16);

        tablaResumen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaResumenMouseClicked(evt);
            }
        });
        tablaResumen.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tablaResumenPropertyChange(evt);
            }
        });
        tablaResumen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tablaResumenKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tablaResumenKeyTyped(evt);
            }
        });
        jScrollPane3.setViewportView(tablaResumen);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(230, 250, 730, 240);

        jButton1.setText("Añadir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(862, 33, 90, 30);

        jButton2.setText("GUARDAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(914, 540, 130, 23);

        btn_tipoAccion.setText("Cargos");
        btn_tipoAccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tipoAccionActionPerformed(evt);
            }
        });
        jPanel1.add(btn_tipoAccion);
        btn_tipoAccion.setBounds(710, 33, 110, 30);

        jLabel4.setText("Habilitar Cargos o Descargos");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(500, 40, 180, 16);

        jButton3.setText("Home");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(20, 520, 72, 23);
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 300, 0, 0);

        txt_descripcionDes.setColumns(1);
        txt_descripcionDes.setLineWrap(true);
        txt_descripcionDes.setRows(2);
        txt_descripcionDes.setTabSize(2);
        txt_descripcionDes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_descripcionDesKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_descripcionDesKeyTyped(evt);
            }
        });
        scroll_desc.setViewportView(txt_descripcionDes);

        jPanel1.add(scroll_desc);
        scroll_desc.setBounds(10, 390, 210, 100);

        lbl_descripcionDes.setText("Descripción del Descargo");
        jPanel1.add(lbl_descripcionDes);
        lbl_descripcionDes.setBounds(40, 370, 140, 16);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Proovedor elegido"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("ID");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 24, 20, -1));

        jLabel5.setText("Nombre");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 55, 50, -1));

        txt_nombreProv.setEditable(false);
        jPanel2.add(txt_nombreProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 52, 130, -1));

        txt_idProv.setEditable(false);
        jPanel2.add(txt_idProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 24, 130, -1));

        jButton4.setText("Eliminar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 240, 210, 120);

        jButton5.setText("Eliminar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(970, 250, 75, 23);

        jLabel8.setText("Valor del movimiento: ");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(250, 530, 130, 16);

        lbl_total.setText("-------");
        jPanel1.add(lbl_total);
        lbl_total.setBounds(410, 530, 160, 16);

        jButton6.setText("Cancelar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(775, 540, 90, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1058, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_proovBKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_proovBKeyReleased

    }//GEN-LAST:event_txt_proovBKeyReleased

    private void txt_proovBKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_proovBKeyTyped
             v.buscarProveedor(tabla_bucarPr, txt_proovB);
    }//GEN-LAST:event_txt_proovBKeyTyped

    private void txt_itemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_itemKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_itemKeyReleased

    private void txt_itemKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_itemKeyTyped
        v.mostrarProducto(tablaItem, txt_item.getText(), listaPAraSolucionarUnBugQueMeDioPerezaArreglarBien);
    }//GEN-LAST:event_txt_itemKeyTyped

    private void txt_proovBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_proovBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_proovBActionPerformed

    private void txt_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_itemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_itemActionPerformed

    private void tablaResumenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaResumenMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaResumenMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     cargos cr = new cargos();
     if(verificarTipo==true){
     cr.tablaResumen(tablaResumen, tablaItem, Detalle_Lista);
     }
     if(verificarTipo==false){
     cr.tablaResumenDescargo(tablaResumen, tablaItem, Detalle_Lista);
     }
     
       cr.valorTotal(Detalle_Lista, lbl_total);
     
     
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tablaResumenKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablaResumenKeyTyped

    }//GEN-LAST:event_tablaResumenKeyTyped

    private void tablaResumenKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablaResumenKeyReleased
      cargos cr = new cargos();
      //RELLENAR TABLA SEGUN TIPO DE MOVIMIENTO
      cr.estadoResumen(tablaResumen, Detalle_Lista, btn_tipoAccion.getText());  
      //recalcular el valor total
      cr.valorTotal(Detalle_Lista, lbl_total);
    }//GEN-LAST:event_tablaResumenKeyReleased

    private void btn_tipoAccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tipoAccionActionPerformed
        cargos cr = new cargos();
        int op;
        if(btn_tipoAccion.getText().equals("Cargos")){
            op=JOptionPane.showConfirmDialog(null, "Pasará a descargos. Recuerde que toda la información seleccionada se eliminará");
            switch (op) {
                case JOptionPane.YES_OPTION:
            verificarTipo=false;
            btn_tipoAccion.setText("Descargos");
            scroll_desc.setVisible(true);
            lbl_descripcionDes.setVisible(true);
            txt_descripcionDes.setVisible(true);
                    break;
                default:
                    throw new AssertionError();
            }
        }else if(btn_tipoAccion.getText().equals("Descargos")){
            op=JOptionPane.showConfirmDialog(null, "Pasará a descargos. Recuerde que toda la información seleccionada se eliminará");
            switch (op) {
                case JOptionPane.YES_OPTION:
            verificarTipo=true;
            scroll_desc.setVisible(false);
            lbl_descripcionDes.setVisible(false);
            txt_descripcionDes.setVisible(false);
            btn_tipoAccion.setText("Cargos");
                    break;
                default:
                    throw new AssertionError();
            }            

        }
        cr.limpiarTodo(tabla_bucarPr, tablaItem, tablaResumen, Detalle_Lista, txt_proovB, txt_item,txt_idProv,txt_nombreProv,txt_descripcionDes,
               lbl_total);
    }//GEN-LAST:event_btn_tipoAccionActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        home ct = new home();
        ct.setLocationRelativeTo(null);
        ct.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tabla_bucarPrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_bucarPrMouseClicked
       cargos cargosObj = new cargos();
       cargosObj.seleccionarProveedor(tabla_bucarPr, txt_idProv, txt_nombreProv);
    }//GEN-LAST:event_tabla_bucarPrMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       txt_idProv.setText(null);
       txt_nombreProv.setText(null);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       cargos cargoObj = new cargos();
       cargoObj.eliminarSeleccionItem(tablaResumen, Detalle_Lista);
       cargoObj.valorTotal(Detalle_Lista, lbl_total);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txt_descripcionDesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_descripcionDesKeyReleased
        
    }//GEN-LAST:event_txt_descripcionDesKeyReleased

    private void txt_descripcionDesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_descripcionDesKeyTyped
           if(txt_descripcionDes.getText().length()>200){
        evt.consume();  
       }
    }//GEN-LAST:event_txt_descripcionDesKeyTyped

    private void tablaResumenPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tablaResumenPropertyChange

    }//GEN-LAST:event_tablaResumenPropertyChange

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      cargos cargosObj = new cargos();
      boolean verificado=false;
        if(!Detalle_Lista.isEmpty() && !txt_idProv.getText().equals("")){
          verificado=true;
      }else{
            JOptionPane.showMessageDialog(null, "Recuerde rellenar toda la información");
        }
        if(verificarTipo==false){
        if(verificado==true && cargosObj.validarRestodeCantidades(Detalle_Lista)==true){
          cargosObj.finalizarMovimiento(Detalle_Lista, txt_idProv, lbl_Fecha, txt_descripcionDes, lbl_total, verificarTipo);
          cargosObj.limpiarTodo(tabla_bucarPr, tablaItem, tablaResumen, Detalle_Lista, txt_proovB, txt_item,txt_idProv,txt_nombreProv,txt_descripcionDes,
               lbl_total);
        } 
        }
          if(verificado==true && verificarTipo==true){
          cargosObj.finalizarMovimiento(Detalle_Lista, txt_idProv, lbl_Fecha, txt_descripcionDes, lbl_total, verificarTipo);
         cargosObj.limpiarTodo(tabla_bucarPr, tablaItem, tablaResumen, Detalle_Lista, txt_proovB, txt_item,txt_idProv,txt_nombreProv,txt_descripcionDes,
               lbl_total);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       cargos cargosObj = new cargos();
       cargosObj.limpiarTodo(tabla_bucarPr, tablaItem, tablaResumen, Detalle_Lista, txt_proovB, txt_item,txt_idProv,txt_nombreProv,txt_descripcionDes,
               lbl_total);
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fmr_Cargo_Descargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fmr_Cargo_Descargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fmr_Cargo_Descargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fmr_Cargo_Descargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fmr_Cargo_Descargo().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_tipoAccion;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbl_Fecha;
    private javax.swing.JLabel lbl_descripcionDes;
    private javax.swing.JLabel lbl_total;
    private javax.swing.JScrollPane scroll_desc;
    private javax.swing.JTable tablaItem;
    private javax.swing.JTable tablaResumen;
    private javax.swing.JTable tabla_bucarPr;
    private javax.swing.JTextArea txt_descripcionDes;
    private javax.swing.JTextField txt_idProv;
    private javax.swing.JTextField txt_item;
    private javax.swing.JTextField txt_nombreProv;
    private javax.swing.JTextField txt_proovB;
    // End of variables declaration//GEN-END:variables
}
