/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formularios;

import Controladores.agregacionesJdbc;
import java.security.InvalidAlgorithmParameterException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.NoSuchPaddingException;
import javax.swing.JOptionPane;

/**
 *
 * @author yisus
 */
public class usuarioCrear_fmr extends javax.swing.JFrame {

    /**
     * Creates new form crearUsuario
     */
    public usuarioCrear_fmr() {
        initComponents();
        passw_txt.setVisible(false);
        passw_Jlbel.setVisible(false);
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        user_cmb = new javax.swing.JComboBox<>();
        id_txt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        nom_txt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        passw_txt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        ape_txt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        dirr_txt = new javax.swing.JTextField();
        passw_Jlbel = new javax.swing.JLabel();
        telefono_txt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jLabel5.setText("Identificación:");

        user_cmb.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        user_cmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Administrador", "Trabajador", "Proveedor","Cliente" }));
        user_cmb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                user_cmbItemStateChanged(evt);
            }
        });
        user_cmb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                user_cmbMouseClicked(evt);
            }
        });
        user_cmb.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                user_cmbPropertyChange(evt);
            }
        });

        id_txt.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        id_txt.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                id_txtInputMethodTextChanged(evt);
            }
        });
        id_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_txtActionPerformed(evt);
            }
        });
        id_txt.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                id_txtPropertyChange(evt);
            }
        });
        id_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                id_txtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                id_txtKeyTyped(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    jButton1ActionPerformed(evt);
                } catch (NoSuchPaddingException ex) {
                    Logger.getLogger(usuarioCrear_fmr.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InvalidAlgorithmParameterException ex) {
                    Logger.getLogger(usuarioCrear_fmr.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });

        jLabel7.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jLabel7.setText("Apellidos:");

        nom_txt.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        nom_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nom_txtActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jLabel8.setText("Nombre:");

        passw_txt.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        passw_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passw_txtActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jLabel9.setText("Tipo de Usuario:");

        ape_txt.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        ape_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ape_txtActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jLabel10.setText("Dirección:");

        dirr_txt.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        dirr_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dirr_txtActionPerformed(evt);
            }
        });

        passw_Jlbel.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        passw_Jlbel.setText("Contraseña:");

        telefono_txt.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        telefono_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefono_txtActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jLabel12.setText("Telefono:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(passw_Jlbel)
                    .addComponent(jLabel12))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(telefono_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                    .addComponent(user_cmb, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dirr_txt, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ape_txt, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nom_txt, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(id_txt, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passw_txt, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(id_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nom_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ape_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(dirr_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(telefono_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(user_cmb, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passw_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passw_Jlbel))
                .addGap(67, 67, 67)
                .addComponent(jButton1)
                .addGap(90, 90, 90))
        );

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 426, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) throws NoSuchPaddingException, InvalidAlgorithmParameterException {//GEN-FIRST:event_jButton1ActionPerformed
    
        if(!id_txt.getText().equals("") && !nom_txt.getText().equals("") && 
        !ape_txt.getText().equals("") && !dirr_txt.getText().equals("") &&
        !telefono_txt.getText().equals("")){
            if(passw_txt.isVisible() && !passw_txt.getText().equals("")){
            agregacionesJdbc cn = new agregacionesJdbc();
            cn.crear_usuario(id_txt, nom_txt, ape_txt, dirr_txt, telefono_txt, user_cmb, passw_txt);
            }else if(!passw_txt.isVisible() && passw_txt.getText().equals("")){
            agregacionesJdbc cn = new agregacionesJdbc();
            cn.crear_usuario(id_txt, nom_txt, ape_txt, dirr_txt, telefono_txt, user_cmb, passw_txt);
            }else{
                JOptionPane.showMessageDialog(null, "Ingrese su contraseña");
            }
    }else{
            JOptionPane.showMessageDialog(null, "Recuerde rellenar todos los campos");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void id_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_txtActionPerformed

    private void nom_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nom_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nom_txtActionPerformed

    private void passw_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passw_txtActionPerformed

    }//GEN-LAST:event_passw_txtActionPerformed

    private void ape_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ape_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ape_txtActionPerformed

    private void dirr_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dirr_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dirr_txtActionPerformed

    private void telefono_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefono_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefono_txtActionPerformed

    private void user_cmbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_user_cmbItemStateChanged
        if(!user_cmb.getSelectedItem().equals("Cliente") || !user_cmb.getSelectedItem().equals("Proveedor")){
            passw_txt.setVisible(false);
            passw_Jlbel.setVisible(false);
        }
        if(user_cmb.getSelectedItem().equals("Administrador") || user_cmb.getSelectedItem().equals("Trabajador")){
           {
        passw_txt.setVisible(true);
        passw_Jlbel.setVisible(true);
            }  
        }
    }//GEN-LAST:event_user_cmbItemStateChanged

    private void user_cmbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user_cmbMouseClicked

    }//GEN-LAST:event_user_cmbMouseClicked

    private void user_cmbPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_user_cmbPropertyChange
 
    }//GEN-LAST:event_user_cmbPropertyChange

    private void id_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_id_txtKeyTyped

    
    }//GEN-LAST:event_id_txtKeyTyped

    private void id_txtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_id_txtKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_id_txtKeyReleased

    private void id_txtPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_id_txtPropertyChange

        
    }//GEN-LAST:event_id_txtPropertyChange

    private void id_txtInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_id_txtInputMethodTextChanged
               Integer id = null;
        id = Integer.valueOf(id_txt.getText());
        if(id==null){
            JOptionPane.showMessageDialog(null, "Solo se pueden agregar numeros enteros!","Advertencia",JOptionPane.INFORMATION_MESSAGE);
            id_txt.setText("");
        }
    }//GEN-LAST:event_id_txtInputMethodTextChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(usuarioCrear_fmr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(usuarioCrear_fmr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(usuarioCrear_fmr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(usuarioCrear_fmr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new usuarioCrear_fmr().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ape_txt;
    private javax.swing.JTextField dirr_txt;
    private javax.swing.JTextField id_txt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField nom_txt;
    private javax.swing.JLabel passw_Jlbel;
    private javax.swing.JTextField passw_txt;
    private javax.swing.JTextField telefono_txt;
    private javax.swing.JComboBox<String> user_cmb;
    // End of variables declaration//GEN-END:variables
}
